steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_IDs/snowwebapp:$COMMIT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/snowwebapp:$COMMIT_SHA']
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   [ 'run',
   'deploy:snowwebapp',
   '--image',
   'gcr.io/$PROJECT_ID/snowwebapp:$COMMIT_SHA',
   '--region',
   'us-central1',
   '--platform',
   'managed',
   '--allow-unauthenticated',
   ]
 images:
 - 'gcr.io/$PROJECT_ID/snowwebapp:$COMMIT_SHA'
